<a href="https://colab.research.google.com/github/VuHoangAnh03/python/blob/main/Ch%C6%B0%C6%A1ng%205.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Thực hành 1: Lăp để tìm nghiệm

In [3]:
x = 3
print (x)

3


In [5]:
import math
x = math.sqrt(1+x)
print (x)

2.0


In [6]:
x = math.sqrt(1+x)
print (x) 

1.7320508075688772


In [7]:
x = math.sqrt(1+x)
print (x) 

1.6528916502810695


Thực hành 2: Lặp bằng while để tìm nghiệm

In [8]:
import math
x = 3
lap = 1
while (x != math.sqrt(x+1)):
 x = math.sqrt(x+1)
 lap = lap +1

x 

1.618033988749895

In [9]:
lap

32

Thực hành 3: Giải phương trình bằng hàm solve trong sympy

In [10]:
 import sympy as sp
from sympy import Symbol
x = Symbol('x')
sp.solve(x-sp.sqrt(1+x),x)

[1/2 + sqrt(5)/2]

Thực hành 4: các phép toán trong vecto

In [11]:
import numpy as np
v1 = np.array([1., 2., 3.]) 
v2 = np.array([2., 1., 0.])
v3 = v1 + v2 
v3

array([3., 3., 3.])

In [12]:
3*v1 + 2*v2 

array([7., 8., 9.])

In [13]:
[1, 2, 3] + [2, 1, 0] 

[1, 2, 3, 2, 1, 0]

In [14]:
3*[1, 2, 3] + 2*[2, 1, 0] 

[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

In [15]:
v4 = np.hstack([v1, v2]) 

In [16]:
np.dot(v1, v2) 

4.0

In [17]:
angles = np.linspace(0, np.pi/2, 5)
angles 

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [18]:
np.sin(angles) 

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

In [19]:
import sympy as sy
sy.sin(angles) 

AttributeError: ignored

In [23]:
 from sympy import sin as sysin
angles = np.linspace(0, np.pi/2, 5)
sinangle = np.zeros(5) 
len(angles)
for i in range(len(angles)):
  sinangle[i] = sysin(angles[i]) 
 sinangle 

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

Thực hành 5: Tính tổng các tích giữa ma trận và vector. Giả định gói thư viện numpy được
đưa vào hệ thống có tên là np

In [26]:
import numpy as np
goc = np.pi/3
A = np.array([ [np.cos(goc), -np.sin(goc)],
  [np.sin(goc), np.cos(goc)] ])
V = np.array([1. , 0. ])
Y = np.dot(A, V)
Y

array([0.5      , 0.8660254])

Thực hành 6: Tính toán đạo hàm trên 1 vector dữ liệu

In [27]:
 from numpy import diff
dx = 0.1
y = [1, 2, 3, 4, 4, 5, 6]
dy = diff(y)/dx
dy 
z = np.array([1, 2, 3, 4, 4, 5, 6])
dz = diff(z)/dx
dz

array([10., 10., 10.,  0., 10., 10.])

In [ ]:
 from numpy import diff
x = [.1, .2, .5, .6, .7, .8, .9]
y = [1, 2, 3, 4, 4, 5, 6]
dydx = diff(y)/diff(x)
print (dydx) 

Thực hành 7: Một số hàm xử lý phẳng (không gian Euclide)

In [30]:
from sympy.geometry import * 
P1 = Point(0, 0)
P2 = Point(3, 4)
P3 = Point(2, -1)
P4 = Point(-1, 5) 

In [31]:
S1 = Segment(P1, P2)
S2 = Segment(P3, P4) 

In [32]:
Point.is_collinear(P1, P2, P3) 

False

In [33]:
 S1.length

5

In [34]:
S2.midpoint

Point2D(1/2, 2)

In [35]:
 S1.slope 

4/3

In [36]:
S1.intersection(S2) 

[Point2D(9/10, 6/5)]

In [37]:
Segment.angle_between(S1, S2)

acos(sqrt(5)/5)

In [38]:
 S1.contains(P3) 

False

In [39]:
L1 = Line(P1, P2)
L1.equation() 

-4*x + 3*y

In [41]:
L1.is_parallel(S1) 

True

In [42]:
L1.is_parallel(S2) 

False

Thực hành 8: Bằng phương pháp đồ thị, hãy cho biết giới hạn của hàm số sau 

In [43]:
import sympy
from sympy import *
x = Symbol('x')
f = x * sin(1/x)
c = Symbol('c')
delta = Symbol('delta')
c = 0
delta = 1/4
sympy.plot(f,(x, c - delta, c + delta))
sympy.plot(f, abs(x), -abs(x),(x, c


SyntaxError: ignored